os:
  - linux
  - osx
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - clang
      - make
      - automake
      - libsdl1.2-dev
      - libogg-dev
      - libsdl-image1.2-dev
      - libcurl4-openssl-dev
      - libopenal-dev
      - libvorbis-dev
      - openssl
      - libssl-dev
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd source/xcode && make ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cd source/src && make && make install; fi
