os:
  - linux
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - clang
      - make
      - automake
      - libsdl1.2-dev
      - libogg-dev
      - libsdl-image1.2-dev
      - libcurl4-openssl-dev
      - libopenal-dev
      - libvorbis-dev
      - openssl
      - libssl-dev
script:
  - cd source/src && make && make install
